# eureka模块项目名称
spring:
  application:
    name: ad-eureka

# 启动端口
server:
  port: 8761

# eureka实例
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# eureka server 1
---
spring:
  application:
    name: ad-eureka
  profiles: server1
server:
  port: 8761
eureka:
  instance:
    hostname: server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/

# eureka server 2
---
spring:
  application:
    name: ad-eureka
  profiles: server2
server:
  port: 8762
eureka:
  instance:
    hostname: server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/

# eureka server 3
---
spring:
  application:
    name: ad-eureka
  profiles: server3
server:
  port: 8763
eureka:
  instance:
    hostname: server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/
