# zuul 启动端口
server:
  port: 8080

# zuul 模块项目名称
spring:
  application:
    name: ad-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 12000
  eureka:
    enabled: true
# zuul配置
zuul:
  prefix: /pikachu
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: ad-search
      strip-prefix: false
    dashboard:
      path: /ad-dashboard/**
      serviceId: ad-dashboard
      strip-prefix: false
