# zuul 启动端口
server:
  port: 8090

# zuul 模块项目名称
spring:
  application:
    name: ad-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

# zuul配置
#zuul:
#  prefix: /pikachu
#  routes:
#    sponsor:
#      path: /ad-sponsor/**
#      serviceId: eureka-client-ad-sponsor
#      strip-prefix: false
#    search:
#      path: /ad-search/**
#      serviceId: eureka-client-ad-search
#      strip-prefix: false
