# 服务相关配置
server:
  port: 8081
  servlet:
    context-path: /ad-sponsor

# Spring相关配置
spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pikachu?autoRecnnect=true&useSSL=false
    username: root
    password: root
    tomcat:
      # 数据库连接池最大连接数
      max-active: 4
      # 最小空闲连接数
      min-idle: 2
      # 初始化连接数
      initial-size: 2

# 注册到eureka上
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      clustor: SPONSOR
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
